### PR TITLE
[feature] Set blockbuilder endpoint via build-time flag for local development

### PR DESCRIPTION
**Pull request by hydrosquall**
- Follow-up to #90, which lets developer use the production blockbuilder backend when developing locally. (https://github.com/enjalot/blockbuilder-search/pull/90#issuecomment-496109354) for more details.
- Uses `cross-env` to make sure environment variable setting works correctly across Mac/Linux/Windows
- I went with specifying the backend via environment variable so people can use other backends if they prefer, but I could also put an "if" switch into the source code with the blockbuilder URL hardcoded if we prefer. I felt this approach is more flexible and involved a smaller amount of additional new code.

cc @micahstubbs 

## Related Issues

- #85

### CODE REVIEW

**Comment by micahstubbs** [comment]
nice, will have a look at this

**Comment by hydrosquall** [comment]
Hi @micahstubbs , wanted to check if you encountered any issues while testing this branch that I could help with.

**Comment by micahstubbs** [comment]
@hydrosquall thanks for asking.  will have another look at this one.  it's been so long, I don't recall.

**Comment by micahstubbs** [comment]
🎉  merged!  thanks for the contribution @hydrosquall.  let me know what's the next PR worth looking at.  maybe #90 now?

**Comment by hydrosquall** [comment]
I think I probably need to rebase/edit some things on that branch, but I
would agree that one is probably the best candidate. Thanks for shepherding
this through :)

**Comment by hydrosquall** [comment]
@micahstubbs I've cleaned up #90, which is ready to revisit whenever you're ready.

**Pull request merged**
