### PR TITLE
[dependencies] Update to React 16, Webpack 4, Babel 7

### PR DESCRIPTION
**Pull request by hydrosquall**
This PR sits on top of changes from #85, but I can drop those commits if that PR doesn't end up getting merged first. It addresses #87 by bringing this project up to the latest react so that people can use current UI libraries to add to the project.

Primary Changes

- Webpack 1 -> 4
- React/React-Dom 14 -> 16
- Pull out the `.babelrc` config file so that parcel and the webpack file can share the configuration.
- Transformed components to use `class` syntax because React.createClass is no longer used in react 16, using this [jscodeshift](https://www.fullstackreact.com/articles/using-jscodeshift-with-react-codemod-to-update-createclass-components-to-es6-classes/)

The preview deploy branch for this set of changes is available here, I believe everything builds correctly.

https://5cd74c6f696d0e00070244d8--blockbuilder-search-hydrosquall.netlify.com/

I also confirmed locally that the package maintains functionality when used with the core `blockbuilder` app using `npm link`.

### CODE REVIEW

**Comment by hydrosquall** [comment]
*Note that bundle.js isn't actually deleted, just dramatically changed, I've heard that Github UI has trouble with displaying large diffs.*

**Comment by micahstubbs** [comment]
@hydrosquall thanks for for upgrading the dependencies! I've been meaning to do this for a while.

curious, could you factor out the changes from https://github.com/enjalot/blockbuilder-search/pull/86, so that this only includes the dependency upgrades?

**Comment by hydrosquall** [comment]
Yes, of course! I should have done that up front, I only mixed them up bc I
didn’t anticipate there being any hurdles with the parcel/netlify proxy
(but was too optimistic).

**Comment by hydrosquall** [comment]
@micahstubbs I pulled out the changes from #86 since that would otherwise have modified package.json, and regenerated the lockfile / bundle.js.

**Comment by micahstubbs** [comment]
nice! will have a look

**Comment by micahstubbs** [comment]
doing some troubleshooting 

```
(py27) ➜  blockbuilder-search git:(hydrosquall-feature/update-to-react-16) ✗ yarn buildWatch
yarn run v1.13.0
$ webpack --color --progress --watch
Hash: d437a155a1da4cdfeeeb
Version: webpack 1.15.0
Time: 36ms
    Asset     Size  Chunks             Chunk Names
bundle.js  3.56 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built] [1 error]

ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/main.js in /Users/m/workspace/blockbuilder-search
 @ multi main
```

**Comment by micahstubbs** [comment]
ok, looks like something is up with the bundle now  🤔 

Screen Shot 2019-05-18 at 1 56 10 PM

```
search:12 GET http://localhost:8889/public-search/bundle.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

**Comment by micahstubbs** [comment]
reading more about this error https://stackoverflow.com/questions/29894154/chrome-neterr-incomplete-chunked-encoding-error

**Comment by micahstubbs** [comment]
interesting, so Firefox gives us a more useful error message:

Screen Shot 2019-05-18 at 1 59 38 PM

```
TypeError: action.data is undefined[Learn More] bundle.js:22875:10
Source map error: SyntaxError: JSON.parse: unterminated string at line 1 column 1428791 of the JSON data
Resource URL: http://localhost:8889/public-search/bundle.js
Source Map URL: data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjay9ib290c3RyYXAgNzAzMmNiNWMwNDNhMGI3ZDU5NGMiLCJ3ZWJwYWNrOi8vLy4vcmVhY3QvbWFpbi5qcyIsIndlYnBhY2s6Ly8vLi9yZWFjdC9zdHlsZS9tYWluLnNjc3M/YzY4OSIsIndlYnBhY2s6Ly8vLi9yZWFjdC9zdHlsZS9tYWluLnNjc3MiLCJ3ZWJwYWNrOi8vLy4vfi9jc3MtbG9hZGVyL2xpYi9jc3MtYmFzZS5qcyIsIndlYnBhY2s6Ly8vLi9+L3N0eWxlLWxvYWRlci9hZGRTdHlsZXMuanMiLCJ3ZWJwYWNrOi8vLy4vfi9yZWFjdC9yZWFjdC5qcyIsIndlYnBhY2s6Ly8vLi9+L3JlYWN0L2xpYi9SZWFjdC5qcyIsIndlYnBhY2s6Ly8vLi9+L3JlYWN0L2xpYi9SZWFjdERPTS5qcyIsIndlYnBhY2s6Ly8vLi9+L3Byb2Nlc3MvYnJvd3Nlci5qcyIsIndlYnBhY2s6Ly8vLi9+L3JlYWN0L2xpYi9SZWFjdEN1cnJlbnRPd25lci5qcyIsIndlYnBhY2s6Ly8vLi9+L3JlYWN0L2xpYi9SZWFjdERPTVRleHRDb21wb25lbnQuanMiLCJ3ZWJwYWNrOi8vLy4vfi9yZWFjdC9saWIvRE9NQ2hpbGRyZW5PcGVyYXRpb25zLmpzIiwid2VicGFjazovLy8uL34v…[Learn More]
```

**Comment by micahstubbs** [comment]
made two small commits to preserve the webpack progress bar feature (looks like it got moved to a plugin sometime between weppack 1 and webpack 4)

**Comment by hydrosquall** [comment]
Thanks for bringing back the color and progress bar functionality :)!

Unfortunately I haven't been able to reproduce the chunked encoding error, but I've gotten it in other projects before if I ran `yarn install` while some form of webpack watch mode was on. Usually restarting watch mode after the yarn install would fix it.

Are you still seeing the incomplete chunked encoding message?

**Comment by hydrosquall** [comment]
I tried out this modified branch together with the docker-compose setup over in https://github.com/enjalot/blockbuilder/pull/232 and it seems to work :)!

**Comment by micahstubbs** [comment]
huh, will take another look. 

I'd like to ensure that the local blockbuilder + local blockbuilder-search UI dev setup still works, as a baseline.

**Comment by micahstubbs** [comment]
Ok, so I am trying this:

1) stopping the `yarn buildWatch` process 
2) `yarn` to install packages
3) restart `yarn buildWatch`

**Comment by micahstubbs** [comment]
strange, still see ` net::ERR_INCOMPLETE_CHUNKED_ENCODING `

**Comment by micahstubbs** [comment]
@hydrosquall what does your environment look like? here's mine:

```
node -v
v11.10.0

yarn -v
1.16.0
```

**Comment by hydrosquall** [comment]
I’ve tried this on both my work and home laptops, on the work laptop I’m
using the same node and yarn versions as you but on my home laptop I’m
using node 12.

Do you run into the chunk issues with yarn build too, or just with
buildWatch?

**Comment by hydrosquall** [comment]
If we end up hitting a standstill in reproducing the chunking issue, what I could try instead is to do a version of https://github.com/enjalot/blockbuilder-search/pull/90 without the library upgrades. This would let us test the search page by itself without needing to spin up `blockbuilder` and go through the whole `npm link` dance. Then we could test all PRs in a clean environment through tools like `codesandbox` or `stackblitz`.

What do you think?

**Comment by micahstubbs** [comment]
@hydrosquall I fixed the chunk encoding problem 🎉 

the solution was:

- use node v12.3.0
- use yarn to install packages for blockbuilder the editor
- some handlebars config changes in PR https://github.com/enjalot/blockbuilder/pull/235

thanks for your patience with this one.  It's important to me to make sure that we keep the current blockbuilder + blockbuilder search working, since this is how we run the site in production currently.  

of course, I'm open to improving how we run the site in production also, but later.  one change at a time 😄

**Comment by micahstubbs** [comment]
so, once I get a review and  enjalot/blockbuilder#235 goes in, we should be able to merge this one too.

**Comment by hydrosquall** [comment]
Woohoo!! Thanks for diving into this so deeply, I’m so happy to see that
this is working.

Maintaining compatibility with the existing production setup makes a lot of
sense to me. We may find a project like nodenv relevant in the future to
ensure people run the expected version of node together with the
application (
https://github.com/nodenv/nodenv )

**Comment by enjalot** [comment]
thanks for doing this and digging in. I'll let @micahstubbs hit the merge button when ready

**Comment by micahstubbs** [comment]
merged! thanks for the contribution @hydrosquall and the review @enjalot 📈

**Pull request merged**
